// ******************************************
// Defini‡”es de cursor - Vers„o em portuguˆs
// Copyright (c) 1994, Hawk Software
// Roberto Falc„o Rocha

// Tipos de cursor

#define APAGADO           0      // Cursor desativado
#define NORMAL            1      // Cursor normal (sob a linha)
#define INSERE            2      // Cursor de inser‡„o (cursor pela metado, em baixo)
#define ESPECIAL1         3      // Cursor especial (cursor cheio)
#define ESPECIAL2         4      // Cursor especial (cursor pela metade, em cima)