// Elementos da barra
#define  HBB_INILIN         1
#define  HBB_INICOL         2
#define  HBB_FINLIN         3
#define  HBB_FINCOL         4
#define  HBB_COR            5
#define  HBB_POSICAO        6

#define  HBB_ELEMENTOS      6

// Seta, barra e fundo
#define  HBB_SETACIMA       CHR(  24 )
#define  HBB_SETABAIXO      CHR(  25 )
#define  HBB_BARRA          CHR( 178 ) 
#define  HBB_FUNDO          CHR( 176 )

